window.CODE_SNIPPETS = window.CODE_SNIPPETS || {};
window.CODE_SNIPPETS["bash"] = [
"for f in *.txt; do\n  echo \"processing ${f}\"\ndone",
"for i in $(seq 1 5); do\n  echo \"count ${i}\"\ndone",
"i=0\nwhile [[ ${i} -lt 5 ]]; do\n  echo \"i=${i}\"\n  i=$((i + 1))\ndone",
"count=10\nuntil [[ ${count} -eq 0 ]]; do\n  echo \"${count}\"\n  count=$((count - 1))\ndone",
"if [[ -f ${file} ]]; then\n  echo \"file exists\"\nelse\n  echo \"missing file\"\nfi",
"if [[ -d ${dir} && -r ${dir} ]]; then\n  echo \"readable dir\"\nfi",
"if [[ ${n} -gt 0 ]]; then\n  echo \"positive\"\nelif [[ ${n} -lt 0 ]]; then\n  echo \"negative\"\nelse\n  echo \"zero\"\nfi",
"if [[ ${str} == h* ]]; then\n  echo \"starts with h\"\nfi",
"greet() {\n  local name=${1:-world}\n  echo \"hello, ${name}\"\n}\ngreet \"sam\"",
"add() {\n  echo $(( $1 + $2 ))\n}\nresult=$(add 3 4)\necho \"${result}\"",
"is_even() {\n  if (( $1 % 2 == 0 )); then\n    return 0\n  fi\n  return 1\n}",
"log() {\n  echo \"[$(date +%H:%M:%S)] $*\"\n}\nlog \"starting up\"",
"case ${1} in\n  start) echo \"starting\" ;;\n  stop) echo \"stopping\" ;;\n  *) echo \"usage: start|stop\" ;;\nesac",
"case ${ext} in\n  jpg|png) echo \"image\" ;;\n  txt|md) echo \"text\" ;;\n  *) echo \"unknown\" ;;\nesac",
"now=$(date +%Y-%m-%d)\necho \"today is ${now}\"",
"count=$(ls -1 | wc -l)\necho \"there are ${count} items\"",
"branch=$(git rev-parse --abbrev-ref HEAD)\necho \"on branch ${branch}\"",
"name=${1:-anonymous}\nhome=${HOME:-/tmp}\necho \"${name} lives in ${home}\"",
"path=\"/usr/local/bin/tool\"\necho \"dir=${path%/*}\"\necho \"base=${path##*/}\"",
"file=\"archive.tar.gz\"\necho \"stem=${file%%.*}\"\necho \"ext=${file##*.}\"",
"fruits=(apple banana cherry)\nfor fruit in \"${fruits[@]}\"; do\n  echo \"${fruit}\"\ndone",
"nums=(4 8 15 16 23)\necho \"count=${#nums[@]}\"\necho \"first=${nums[0]}\"",
"declare -A ages\nages[alice]=30\nages[bob]=25\nfor key in \"${!ages[@]}\"; do\n  echo \"${key}=${ages[$key]}\"\ndone",
"while IFS= read -r line; do\n  echo \"line: ${line}\"\ndone < input.txt",
"while IFS=, read -r name age; do\n  echo \"${name} is ${age}\"\ndone < people.csv",
"grep -c \"error\" log.txt\nawk '{ sum += $1 } END { print sum }' nums.txt",
"ps aux | awk '{ print $2 }' | sort -n | head\nsed 's/foo/bar/g' input.txt > output.txt",
"if grep -q \"TODO\" main.sh; then\n  echo \"found todo\"\nfi\necho \"exit code: $?\"",
"while getopts \"n:v\" opt; do\n  case ${opt} in\n    n) name=${OPTARG} ;;\n    v) verbose=1 ;;\n  esac\ndone",
"cat <<EOF\nname: ${USER}\nshell: ${SHELL}\nEOF"
];
