window.CODE_SNIPPETS = window.CODE_SNIPPETS || {};
window.CODE_SNIPPETS["quotes"] = [
`Talk is cheap. Show me the code. - Linus Torvalds`,
`Premature optimization is the root of all evil. - Donald Knuth`,
`Beware of bugs in the above code; I have only proved it correct, not tried it. - Donald Knuth`,
`Simplicity is prerequisite for reliability. - Edsger W. Dijkstra`,
`Program testing can be used to show the presence of bugs, but never to show their absence. - Edsger W. Dijkstra`,
`The competent programmer is fully aware of the limited size of his own skull. - Edsger W. Dijkstra`,
`Simplicity and elegance are unpopular because they require hard work and discipline. - Edsger W. Dijkstra`,
`Debugging is twice as hard as writing the code in the first place. - Brian Kernighan`,
`Controlling complexity is the essence of computer programming. - Brian Kernighan`,
`Don't comment bad code, rewrite it. - Brian Kernighan`,
`The most effective debugging tool is still careful thought, coupled with judiciously placed print statements. - Brian Kernighan`,
`Any fool can write code that a computer can understand. Good programmers write code that humans can understand. - Martin Fowler`,
`Any organization that designs a system will produce a design whose structure is a copy of the organization's communication structure. - Melvin Conway`,
`The cheapest, fastest, and most reliable components are those that aren't there. - Gordon Bell`,
`There are only two hard things in Computer Science: cache invalidation and naming things. - Phil Karlton`,
`Make it work, make it right, make it fast. - Kent Beck`,
`The function of good software is to make the complex appear to be simple. - Grady Booch`,
`Programs must be written for people to read, and only incidentally for machines to execute. - Harold Abelson`,
`Theory and practice sometimes clash. And when that happens, theory loses. Every single time. - Linus Torvalds`,
`C makes it easy to shoot yourself in the foot; C++ makes it harder, but when you do it blows your whole leg off. - Bjarne Stroustrup`,
`There are only two kinds of languages: the ones people complain about and the ones nobody uses. - Bjarne Stroustrup`,
`The most important property of a program is whether it accomplishes the intention of its user. - C.A.R. Hoare`,
`Premature optimization is the root of all evil in programming. - C.A.R. Hoare`,
`UNIX is simple. It just takes a genius to understand its simplicity. - Dennis Ritchie`,
`The best way to predict the future is to invent it. - Alan Kay`,
`Measuring programming progress by lines of code is like measuring aircraft building progress by weight. - Bill Gates`,
`Walking on water and developing software from a specification are easy if both are frozen. - Edward Berard`,
`The best performance improvement is the transition from the nonworking state to the working state. - John Ousterhout`,
`Focused, hard work is the real key to success. - John Carmack`,
`Low-level programming is good for the programmer's soul. - John Carmack`,
`Software is a great combination of artistry and engineering. - Bill Gates`,
`Computers are good at following instructions, but not at reading your mind. - Donald Knuth`,
`An algorithm must be seen to be believed. - Donald Knuth`,
`Science is what we understand well enough to explain to a computer; art is everything else. - Donald Knuth`,
`Programming is the art of telling another human what one wants the computer to do. - Donald Knuth`,
`We can only see a short distance ahead, but we can see plenty there that needs to be done. - Alan Turing`,
`A computer would deserve to be called intelligent if it could deceive a human into believing that it was human. - Alan Turing`,
`Sometimes it is the people no one imagines anything of who do the things that no one can imagine. - Alan Turing`,
`To err is human, but to really foul things up you need a computer. - Paul Ehrlich`,
`The question of whether a computer can think is no more interesting than whether a submarine can swim. - Edsger W. Dijkstra`,
`It is not enough to be busy, so are the ants. The question is: what are we busy about? - Henry David Thoreau`,
`The only way to learn a new programming language is by writing programs in it. - Dennis Ritchie`,
`Good code is its own best documentation. - Steve McConnell`,
`The act of describing a program in unambiguous detail and the act of programming are one and the same. - Kevlin Henney`,
`A ship in harbor is safe, but that is not what ships are built for. - John A. Shedd`,
`It always seems impossible until it's done. - Nelson Mandela`,
`The journey of a thousand miles begins with a single step. - Lao Tzu`,
`Whether you think you can, or you think you can't, you're right. - Henry Ford`,
`Success is not final, failure is not fatal: it is the courage to continue that counts. - Winston Churchill`,
`The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt`,
`I have not failed. I've just found 10,000 ways that won't work. - Thomas Edison`,
`Genius is one percent inspiration and ninety-nine percent perspiration. - Thomas Edison`,
`The best time to plant a tree was 20 years ago. The second best time is now. - Chinese Proverb`,
`Stay hungry, stay foolish. - Steve Jobs`,
`Innovation distinguishes between a leader and a follower. - Steve Jobs`,
`Your time is limited, so don't waste it living someone else's life. - Steve Jobs`,
`If you want to go fast, go alone. If you want to go far, go together. - African Proverb`,
`Knowledge speaks, but wisdom listens. - Jimi Hendrix`,
`The only true wisdom is in knowing you know nothing. - Socrates`,
`First they ignore you, then they laugh at you, then they fight you, then you win. - Mahatma Gandhi`,
`Be the change that you wish to see in the world. - Mahatma Gandhi`,
`Imagination is more important than knowledge. - Albert Einstein`,
`Logic will get you from A to Z; imagination will get you everywhere. - Albert Einstein`,
`The important thing is not to stop questioning. - Albert Einstein`,
`Weeks of programming can save you hours of planning. - Anonymous`,
`Code never lies, comments sometimes do. - Ron Jeffries`,
`The most disastrous thing that you can ever learn is your first programming language. - Alan Kay`,
`A language that doesn't affect the way you think about programming is not worth knowing. - Alan Perlis`,
`Simplicity is the soul of efficiency. - Austin Freeman`,
`Real artists ship. - Steve Jobs`
];
